### ISSUE TITLE
Does not support trailing descriptor (informal) signatures

### ISSUE THREAD

**Issue by simonbuchan** [quentinadam/deno-zip#1]
As described in APPNOTE.TXT:

> 4.3.9.3 Although not originally assigned a signature, the value
>         0x08074b50 has commonly been adopted as a signature value
>         for the data descriptor record.  Implementers SHOULD be
>         aware that ZIP files MAY be encountered with or without this
>         signature marking data descriptors and SHOULD account for
>         either case when reading ZIP files to ensure compatibility.

In other words, the local entry for such files looks like:

```
[header...] [data...] "PK\7\8" crc32  compressed_size uncompressed_size
```

The AWS CloudFormation resource schema is (currently?) an example of such a file: https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip

**Comment by simonbuchan** [comment]
Same issue in `jsr:@zip-js/zip-js`: https://github.com/gildas-lormeau/zip.js/issues/539

**Comment by quentinadam** [comment]
Hello @simonbuchan.

Thank you for using my simple zip library. I looked into the provided AWS CloudformationSchema zip file and it appears that the issue lies with the fact that the crc32, compressed size and uncompressed size fields of the file entry are set to 0, and that they therefore should be read from the directory entry.
I have updated the library (https://github.com/quentinadam/deno-zip/commit/ca9b2372875611efec8ad4c9e812b7622863a082) to take that into account and version 0.1.2 should now work to extract your zip file.
